# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailed', models.BooleanField(default=False)),
                ('userOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_user_one', to=settings.AUTH_USER_MODEL)),
                ('userTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_user_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
